### ISSUE TITLE
cua mode

### ISSUE THREAD

**Issue by jney** [mattfidler/tabbar-ruler.el#14]
i can cut a region with C-x using cua-mode. but when tabbar-ruler is active in my project it doesn't work properly.

**Comment by mlf176f2** [comment]
Hm.  Have you tried 

```lisp

(setq tabbar-ruler-movement-timer-delay 10000)

```

It may be that the timer is interfering with CUA-mode's timer...

**Comment by mattfidler** [comment]
I'm assuming this works now.
