### ISSUE TITLE
setting left tabbar-ruler-fancy-tab-separator

### ISSUE THREAD

**Issue by rhoit** [mattfidler/tabbar-ruler.el#23]
I'm trying to change the fancy-tab-separator using powerline theme, but couldn't get the left side working. 

i have commented out the powerline section.
https://gist.github.com/rhoit/b88e43b47c7180c7d00c#file-tabbar-ruler_mod-el-L542-L557

but same thing worked here.
https://gist.github.com/rhoit/b88e43b47c7180c7d00c#file-tabbar-ruler_mod-el-L628-L634

now it looks something like this. 
![screenshot53](https://cloud.githubusercontent.com/assets/1684754/12024235/1e2d6b94-adca-11e5-9833-9f75d5bdef82.png)

**Comment by krazedkrish** [comment]
trying using mode line theme in tabbar-rule, cool hack :+1:

**Comment by mattfidler** [comment]
That's cool.   I will look into it on Monday

**Comment by mattfidler** [comment]
This should do the trick.

**Comment by mattfidler** [comment]
Use 
```lisp
(setq tabbar-ruler-fancy-tab-separator 'rounded)
```

**Comment by mattfidler** [comment]
The default is still text.  Based on color themes used, the outcome is not pretty unless you use text.  For example:

![image](https://cloud.githubusercontent.com/assets/514778/12180922/d9862f3a-b544-11e5-8a5b-fa18605aa925.png)


vs the text version

![image](https://cloud.githubusercontent.com/assets/514778/12180946/fde78cb6-b544-11e5-9aac-9505e63c0ff7.png)

**Comment by rhoit** [comment]
seems really pretty in my config, :+1: just pulled it today!
![screenshot60](https://cloud.githubusercontent.com/assets/1684754/12304188/5deb9c4a-ba56-11e5-82c4-365be18ccc32.png)

**Comment by mattfidler** [comment]
Great! 

I think the issue is font size but I'm unsure.
