### ISSUE TITLE
How to have tabbar-ruler without using mode-icons?

### ISSUE THREAD

**Issue by boudiccas** [mattfidler/tabbar-ruler.el#35]
How to have tabbar-ruler without using mode-icons please? I'm fed up with every time that I do a package update I get a new mode-icons package which screws up all the present working icons, so I have to restart emacs.

**Comment by shanemikel** [comment]
put (mode-icons-mode -1) in your config

**Comment by mattfidler** [comment]
Thanks.  That indeed works.

**Comment by shanemikel** [comment]
@mattfidler , you might want to close the issue
