### ISSUE TITLE
3eb5e2d is causing cursor scrolling to be invisible

### ISSUE THREAD

**Issue by obadz** [mattfidler/tabbar-ruler.el#37]
On 3eb5e2d2778c015f9489011fd86ff403869766db and later (introduced in #27), once the tabs are visible, holding the arrow down key to scroll makes the cursor in my emacs invisible. The cursor becomes visible again once I lift my finger. Unfortunately this means I find out where the cursor went only once I've lifted my finger which makes it impossible to aim :-(

**Comment by mattfidler** [comment]
You could disable mode-icons to see if the scrolling returns.

**Comment by obadz** [comment]
Yes forgot to mention I still have the problem with
```elisp
(setq tabbar-ruler-use-mode-icons nil)
```

**Comment by mattfidler** [comment]
Has this been fixed for you?

**Comment by obadz** [comment]
Ha, didn't see the new commit, will try shortly.

**Comment by obadz** [comment]
Yes this fixed it, thanks!

cc @ryuslash
