### ISSUE TITLE
new issue after update

### ISSUE THREAD

**Issue by danboice** [mattfidler/tabbar-ruler.el#38]
Hi, I'm getting a new issue after a recent update.  Here is the debug output. Looks like it has something to do with the mode-icons.  I tried reinstalling it and mode-icons and it is still giving me the same error.  Thanks.  I love it btw.

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  xw-color-values(nil nil)
  color-values(nil nil)
  color-name-to-rgb(nil)
  mode-icons-get-icon-display-xpm-bw-face("~/.emacs.d/elpa/mode-icons-20160501.2246/icons/helm.xpm" mode-line-inactive)
  mode-icons-get-icon-display("helm" xpm-bw nil nil)
  mode-icons-propertize-mode("Helm" ("\\` ?Helm\\'" "helm" xpm-bw))
  mode-icons-set-minor-mode-icon()
  mode-icons-mode()
  byte-code("\302\303\304\206	\305 !\"\210\306\307!\210\306\310!\210\306\311!\210\306\312!\210\306\313\314\315#\210\316\317\314\320\321\310%\210\322\323\315\324\325\326\321\317&\210\322\327\314\330\325\326\321\317&\210\322\331\314\332\325\326\321\317&\210\322\333\314\334\325\326\321\317&\210\322\335\314\336\325\326\321\317&\210\322\337\340\341\325\342\321\317&\210\322\343\344\345\325\342\321\317&\210\322\346\347\350\325\342\321\317&\210\322\351\352\353\325\354\321\317&\210\322\355\356\357\325\360\321\317&\210\322\301\315\361\325\362\321\317&\210\322\363\315\364\325\365\321\317&\210	\203\310\306\313\314\315#\210\366\367!\203\304\367 \210\202\310\370\371!\210\322\372\314\373\325\326\321\317&\210\322\374\314\375\325\376\321\317&\210\322\377\201@\201A\325\201B\321\317&\210\322\201C\201D\201E\325\201F\321\317&\210\322\201G\314\201H\325\201I\321\317&\210\322\201J\315\201K\325\326\321\317&\210\322\201L\201M\201N\325\201O\321\317&\210\322\201P\314\201Q\325\326\321\317&\210\322\201R\201S\201T\325\201U\321\317&\207" [load-file-name tabbar-ruler-use-mode-icons add-to-list load-path file-name-directory buffer-file-name require cl-lib tabbar easymenu powerline mode-icons nil t custom-declare-group tabbar-ruler "Pretty tabbar, autohide, use both tabbar/ruler." :group custom-declare-variable tabbar-ruler-global-tabbar "Should tabbar-ruler have a global tabbar?" :type boolean tabbar-ruler-global-ruler "Should tabbar-ruler have a global ruler?" tabbar-ruler-popup-menu "Should tabbar-ruler have a popup menu.  As mouse moves toward top of window, the menu pops up." tabbar-ruler-popup-toolbar "Should tabbar-ruler have a popup toolbar.  As mouse moves toward top of window, the toolbar pops up." tabbar-ruler-popup-scrollbar "Should tabbas-ruler have popup scrollbar.  As mouse moves, the scroll-bar pops up.  Otherwise the sroll-bar is turned off." tabbar-ruler-popup-menu-min-y 5 "Minimum number of pixels from the top before a menu/toolbar pops up." integer tabbar-ruler-popup-menu-min-y-leave 50 "Minimum number of pixels form the top before a menu/toolbar disappears." tabbar-ruler-do-not-switch-on-ruler-when-tabbar-is-on-y 75 "Minimum number of pixels to switch on ruler when tabbar is on." tabbar-ruler-excluded-buffers (quote ("*Messages*" "*Completions*" "*ESS*")) "Excluded buffers in tabbar." (repeat (string :tag "Buffer Name")) tabbar-ruler-fight-igore-modes (quote (info-mode helm-mode package-menu-mode)) "Exclude these mode when changing between tabbar and ruler." (repeat (symbol :tag "Major Mode")) "Use mode icons for tabbar-ruler." ...] 8)
  #<subr require>(tabbar-ruler nil nil)
  ad-Advice-require(#<subr require> tabbar-ruler)
  apply(ad-Advice-require #<subr require> tabbar-ruler)
  require(tabbar-ruler)
  eval((require (quote tabbar-ruler)) nil)
  eval-last-sexp-1(nil)
  #[257 "\204\303!\207	\303!\n)B\211A	=\204\211A\211@\207" [eval-expression-debug-on-error eval-last-sexp-fake-value debug-on-error eval-last-sexp-1] 4 2471727 "P"](nil)
  ad-Advice-eval-last-sexp(#[257 "\204\303!\207	\303!\n)B\211A	=\204\211A\211@\207" [eval-expression-debug-on-error eval-last-sexp-fake-value debug-on-error eval-last-sexp-1] 4 2471727 "P"] nil)
  apply(ad-Advice-eval-last-sexp #[257 "\204\303!\207	\303!\n)B\211A	=\204\211A\211@\207" [eval-expression-debug-on-error eval-last-sexp-fake-value debug-on-error eval-last-sexp-1] 4 2471727 "P"] nil)
  eval-last-sexp(nil)
  #<subr call-interactively>(eval-last-sexp nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> eval-last-sexp nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (eval-last-sexp nil nil))
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)

**Comment by mattfidler** [comment]
What is your color theme?

**Comment by mattfidler** [comment]
This should be fixed.

**Comment by mattfidler** [comment]
Does this work for you out now
