### ISSUE TITLE
Error during redisplay: (eval (tabbar-line)) signaled (wrong-type-argument consp nil)

### ISSUE THREAD

**Issue by jingqi** [mattfidler/tabbar-ruler.el#39]
When I got the newest version of tabbar-ruler, and tried to open Emacs in terminal with argument -nw, I got an error of this:

> Error during redisplay: (eval (tabbar-line)) signaled (wrong-type-argument consp nil)

I'm at Mac terminal with GNU Emacs, and the error raised from here:
1. `tabbar-line-format` calls `tabbar-line-tab`
2. In `tabbar-line-tab`, variable `close-buttong-image` gets a `nil` value, in tabbar-ruler.el at line 1384
3. `tabbar-line-tab` calls `tabbar-normalize-image` at line 1393, with a `nil` image
4. Finally an error raised in `tabbar-normalize-image` at line 1113, by expression:
`(setcdr image plist)`

The function `tabbar-find-image` in tabbar will always return `nil` dues to `(display-images-p)` always returns false. So I think maybe `tabbar-normalize-image` should check the first argument to avoid raising error.
I temporarily override this in my .emacs file
```
(defadvice tabbar-normalize-image (around check-first-arg activate)
   (when (ad-get-arg 0)
    ad-do-it))
```

**Comment by mattfidler** [comment]
Thank you.  I'm sorry it took so long.
