### ISSUE TITLE
unnecessary tabs

### ISSUE THREAD

**Issue by danboice** [mattfidler/tabbar-ruler.el#40]
![screenshot 2016-05-19 19 28 10](https://cloud.githubusercontent.com/assets/1483796/15415476/c5c52df4-1df7-11e6-93e5-a34339fe6b07.png)

Every time I use helm-m-x it opens a tab for the minibuffer that doesn't go away.  Packages, customizing options, etc.  Even though they are supposed to be excluded.  When they are on the excluded list, the tabbar does not appear and it makes it more difficult to close, but the tab for the buffer appears when you go to other buffers that aren't excluded.  Then you need to manually kill each buffer that should kill automatically.  Thanks.
![screenshot 2016-05-19 19 40 56](https://cloud.githubusercontent.com/assets/1483796/15415727/92e8f4ea-1df9-11e6-9e8c-e880d46894d3.png)

![screenshot 2016-05-19 19 33 33](https://cloud.githubusercontent.com/assets/1483796/15415620/94e4a38a-1df8-11e6-917a-ece55f42167c.png)

**Comment by mattfidler** [comment]
Sorry for the delay in response.  It seems to me you are using `*helm-Mx*` but should be using `*helm M-x*`, but I agree if that is fixed, `*helm M-x*` is still displayed on the list of buffers.

**Comment by mattfidler** [comment]
It should be fixed.  It works for me now.  If it doesn't work for you, let me know.
