### ISSUE TITLE
2 rows of tabs?

### ISSUE THREAD

**Issue by boudiccas** [mattfidler/tabbar-ruler.el#41]
Is it possible to have tabbar-ruler to use 2 rows of tabs please? This would really help where I'm working with big projects.

**Comment by mattfidler** [comment]
You have a great point.  It would be great to have two rows.

`tabbar-mode` is implemented with the variable `header-line-format`.  Currently this only supports a single line.  

For example, without `tabbar-mode` enabled:

```lisp
(setq header-line-format "test\ntest2")
```

should be on two lines for this to work.  However, you get:

![image](https://cloud.githubusercontent.com/assets/514778/15597730/b0eefa80-2398-11e6-8ddf-dd277f7df9a2.png)


Sorry :(
