### ISSUE TITLE
tab font slant

### ISSUE THREAD

**Issue by transtone** [mattfidler/tabbar-ruler.el#43]
why the tabbar font become to slant after update?

![6](https://cloud.githubusercontent.com/assets/46688/15999055/77200ed0-3175-11e6-9df2-805706e91cdc.png)

**Comment by rhoit** [comment]
I guess its means tabs buffer aren't saved. :wink:

**Comment by transtone** [comment]
as u see, the unsaved buffer is orange, not slant.

**Comment by mattfidler** [comment]
Hm.  I'm unsure. Perhaps it was a transient bug with variable pitch fonts.
