### ISSUE TITLE
tabbar-selected is still blue when using dark theme

### ISSUE THREAD

**Issue by zijianyue** [mattfidler/tabbar-ruler.el#46]
That make it hard to see the text clearly, I'm using spacemacs dark theme

**Comment by boudiccas** [comment]
i totally agree. I've been trying to find some way round this unreadable blue text, but haven't succeeded.. Can you help please Mat? Could we not have the option of setting the colour of text that we want for the selected tab please?

**Comment by mattfidler** [comment]
it should just be a face.  I can't recall what is is though.

**Comment by zijianyue** [comment]
Could you please adjust it to fit the theme

**Comment by mattfidler** [comment]
For me, this was changed back with the latest commit.
