### ISSUE TITLE
title splash bug

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [mattfidler/tabbar-ruler.el#48]
when i press key up or down, the tab changed like this
![title](https://cloud.githubusercontent.com/assets/7458713/17837230/94f23334-67df-11e6-90de-9db7ab44870e.png)

after i moved the mouse cursor, the tab change to normal mode.

i test it with in a clean emacs enviroment, no other plugin installed, no other custom el configs

**Comment by mattfidler** [comment]
did you fix this?  it's just an option.

**Comment by ziyouchutuwenwu** [comment]
i commented option

```
(setq tabbar-ruler-global-ruler t)
```

thank you very much!

**Comment by mattfidler** [comment]
It's a feature.  you cannot currently have both a
tabbar-ruler.el@noreply.github.com and a ruler.
