### ISSUE TITLE
feature request map *mouse-menu-buffer*

### ISSUE THREAD

**Issue by rhoit** [mattfidler/tabbar-ruler.el#51]
will it be possible to map the 

*mouse-menu-buffer* 

![image](https://user-images.githubusercontent.com/1684754/36838064-346bfe08-1d66-11e8-889a-3fefaac0e2cb.png)

to *tabbar-default-button* may be with Control

![image](https://user-images.githubusercontent.com/1684754/36838088-49665178-1d66-11e8-89e2-10b9bfbc1ad3.png)

**Comment by mattfidler** [comment]
Yes it is possible.  The mouse is simply a keymap in emacs.

**Comment by mattfidler** [comment]
```lisp
(global-set-key (kbd "<C-down-mouse-1>") 'tabbar-context-menu) 
````

**Comment by rhoit** [comment]
thanks, I dunno what I was thinking yesterday, I could have tried `M-x` `global-set-key` set keys and find the respective thing with `C-h` `k`

![image](https://user-images.githubusercontent.com/1684754/36902514-ce805e66-1e52-11e8-811d-68b1ce3a3277.png)

```
     (define-key global-map (kbd "<header-line> <down-mouse-1>") 'mouse-buffer-menu)
```
finally working!, sorry the trouble.

![image](https://user-images.githubusercontent.com/1684754/36902280-09caafcc-1e52-11e8-8511-53fb490615ff.png)

**Comment by mattfidler** [comment]
No Problem.
