### ISSUE TITLE
Is this package still active?

### ISSUE THREAD

**Issue by ema2159** [mattfidler/tabbar-ruler.el#56]
Is seems that it has been quite some time since the last update on this package. I use it a lot, and wanted to know if this package is still active.

**Comment by mattfidler** [comment]
I depends on what you mean by alive.  I still use it :)  But if you want to
update it feel free.

**Comment by mattfidler** [comment]
Also if you want to take over the maintainence, please let me know.

**Comment by ema2159** [comment]
That would be nice! Although I need to study the code a little bit before. There are several enhancements that I would like to implement like integrating all the icons for example.

**Comment by mattfidler** [comment]
Currently the icons are in mode-icons which has been actively maintained.
Feel free to submit new icons there:

https://github.com/ryuslash/mode-icons/issues

**Comment by ema2159** [comment]
Yes, I understand that and I've contributed to that package also, but some people use all the icons and may want to keep consistency with the icons through all their configuration so it would be nice to have the option, the more customization options the better! Also, is there a way to configure this package with use package? I've tried but I've not been able to do it

**Comment by mattfidler** [comment]
I could see the desire for icon themes.  I think they mske more sense in
mode icons though and then pair a color theme with an icon theme...

I have not used the use-package route. If you fogure spmerhing out feel
free to document it too.

**Comment by ema2159** [comment]
That's a good idea, I'll try to figure out how to do it.
I haven't found the way of installing tabbar-ruler with use-package. I has to do with it not being initialized by a function but by a custom.
